version: '3'

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - go-app-network

  go-app:
    image: gildembergleite/revisao-golang-ittalent
    ports:
      - "8080:8080"
    networks:
      - go-app-network
    depends_on:
      - mongodb

  linux-client:
    image: ubuntu
    networks:
      - go-app-network
    volumes:
      - go-app-volume:/app
    depends_on:
      - mongodb
    command: >
      bash -c "
        tail -f /dev/null && 
        apt-get update && 
        apt-get install -y curl vim-tiny htop
      "

networks:
  go-app-network:

volumes:
  mongodb_data:
  go-app-volume:
