services:
  db:
    container_name: db
    image: mongo
    restart: always
    networks:
      - api-net
    volumes:
      - db:/data/db
      
  api:
    container_name: api
    image: gildembergleite/revisao-golang-ittalent
    restart: always
    networks:
      - api-net
    depends_on:
      - db
    environment:
      MONGO_DB_HOST: db

  
  client:
    container_name: client
    image: ubuntu
    networks:
      - api-net
    tty: true
    command: bash -c "apt-get update && apt-get install -y curl vim-tiny htop && tail -f /dev/null"

networks:
  api-net:
    name: api-net
    driver: bridge

volumes:
  db:
    name: db
